server:
  port: 7070
eureka:
  instance:
    hostname: 127.0.0.1
    #服务名称
    appname: eureka-server
  client:
    service-url:
      #注册中心的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    #是否向注册中心注册自己，默认为true，
    #由于只是单节点(之后会分享高可用的Eureka集群的搭建)，所以这里选择false
    register-with-eureka: false
    #是否检索服务，由于注册中心的职责是维护服务示例，默认为true
    #并不需要检索服务，所以这里选择false
    fetch-registry: false

